### ISSUE TITLE
chlorophyll

### ISSUE THREAD

**Issue by nikkidix** [GTMNERR/2022-swmp-annual-report#10]
In this sentence: "San Sebastian and Pellicer Creek continued to see high chlorophyll at those sites ([Figure 5.4 (b)]; [Figure 5.4 (d)].", 
did you mean to say Pellicer Creek? CHL went down after Jan and was below avg until summer.

Also, I suggest deleting this sentence "Values were much lower (some even below threshold levels) at all sites in the last quarter of the year."

**Comment by skdunnigan** [comment]
addressed in commit dd1ee90
